# Generated by Django 6.0.2 on 2026-02-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_skill_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='extracted_skills',
            field=models.TextField(blank=True),
        ),
    ]
