# Generated by Django 6.0.2 on 2026-02-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_resume_extracted_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category_choice',
            field=models.CharField(choices=[('language', 'Programing Language'), ('framework', 'Framework'), ('database', 'Database'), ('tool', 'Tool')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
