# Generated by Django 6.0.2 on 2026-02-07 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_skill_category_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='category_choice',
            new_name='category',
        ),
    ]
