# Generated by Django 5.2.7 on 2026-02-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_rename_category_choice_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experince_level',
            field=models.CharField(choices=[('fresher', 'Fresher'), ('junior', 'Junior (1-3 years)'), ('mid', 'Mid (3-5 years)'), ('senior', 'Senior (5+ years)')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='role_type',
            field=models.CharField(choices=[('intership', 'Intership'), ('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
