# Generated by Django 5.2.7 on 2026-02-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_job_experince_level_job_role_type_alter_job_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='experince_level',
            new_name='experience_level',
        ),
        migrations.AlterField(
            model_name='job',
            name='role_type',
            field=models.CharField(choices=[('internship', 'Internship'), ('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
